services:
  - type: web
    name: orbit
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 'app:socketio.run(app)'
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
