services:
  - type: web
    name: orbit11
    env: python
    buildCommand: |
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      gunicorn --worker-class gevent -w 4 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: orbit11db
    databaseName: orbit11
    user: orbit11user
    plan: free
